# Generated from the provider's pinned SQLite source fixture.
# Edit the generator inputs, then regenerate; do not edit this file by hand.

entity "departments" {
  key = ["dept_no"]

  property "dept_no" {
    required = true
    type = "string"
  }

  property "dept_name" {
    required = true
    type = "string"
  }
}

entity "dept_emp" {
  key = ["emp_no","dept_no"]

  property "emp_no" {
    required = true
    entity = "employees"
  }

  property "dept_no" {
    required = true
    entity = "departments"
  }

  property "from_date" {
    required = true
    type = "string"
  }

  property "to_date" {
    required = true
    type = "string"
  }
}

entity "dept_manager" {
  key = ["emp_no","dept_no"]

  property "emp_no" {
    required = true
    entity = "employees"
  }

  property "dept_no" {
    required = true
    entity = "departments"
  }

  property "from_date" {
    required = true
    type = "string"
  }

  property "to_date" {
    required = true
    type = "string"
  }
}

entity "employees" {
  key = ["emp_no"]

  property "emp_no" {
    required = true
    type = "int"
  }

  property "birth_date" {
    required = true
    type = "string"
  }

  property "first_name" {
    required = true
    type = "string"
  }

  property "last_name" {
    required = true
    type = "string"
  }

  property "gender" {
    required = true
    type = "string"
  }

  property "hire_date" {
    required = true
    type = "string"
  }
}

entity "salaries" {
  key = ["emp_no","from_date"]

  property "emp_no" {
    required = true
    entity = "employees"
  }

  property "salary" {
    required = true
    type = "int"
  }

  property "from_date" {
    required = true
    type = "string"
  }

  property "to_date" {
    required = true
    type = "string"
  }
}

entity "titles" {
  key = ["emp_no","title","from_date"]

  property "emp_no" {
    required = true
    entity = "employees"
  }

  property "title" {
    required = true
    type = "string"
  }

  property "from_date" {
    required = true
    type = "string"
  }

  property "to_date" {
    type = "string"
  }
}
