# Generated from the provider's pinned SQLite source fixture.
# Edit the generator inputs, then regenerate; do not edit this file by hand.
# SPDX-License-Identifier: CC-BY-SA-3.0

record "departments" {
  key = ["dept_no"]

  field "dept_no" {
    required = true
    type = "string"
  }

  field "dept_name" {
    required = true
    type = "string"
  }
}

record "dept_emp" {
  key = ["emp_no","dept_no"]

  field "emp_no" {
    required = true
    record = "employees"
  }

  field "dept_no" {
    required = true
    record = "departments"
  }

  field "from_date" {
    required = true
    type = "string"
  }

  field "to_date" {
    required = true
    type = "string"
  }
}

record "dept_manager" {
  key = ["emp_no","dept_no"]

  field "emp_no" {
    required = true
    record = "employees"
  }

  field "dept_no" {
    required = true
    record = "departments"
  }

  field "from_date" {
    required = true
    type = "string"
  }

  field "to_date" {
    required = true
    type = "string"
  }
}

record "employees" {
  key = ["emp_no"]

  field "emp_no" {
    required = true
    type = "int"
  }

  field "birth_date" {
    required = true
    type = "string"
  }

  field "first_name" {
    required = true
    type = "string"
  }

  field "last_name" {
    required = true
    type = "string"
  }

  field "gender" {
    required = true
    type = "string"
  }

  field "hire_date" {
    required = true
    type = "string"
  }
}

record "salaries" {
  key = ["emp_no","from_date"]

  field "emp_no" {
    required = true
    record = "employees"
  }

  field "salary" {
    required = true
    type = "int"
  }

  field "from_date" {
    required = true
    type = "string"
  }

  field "to_date" {
    required = true
    type = "string"
  }
}

record "titles" {
  key = ["emp_no","title","from_date"]

  field "emp_no" {
    required = true
    record = "employees"
  }

  field "title" {
    required = true
    type = "string"
  }

  field "from_date" {
    required = true
    type = "string"
  }

  field "to_date" {
    type = "string"
  }
}
